-- Create Plumbers Table
create table plumbers (
  id bigint generated by default as identity primary key,
  name text not null,
  rating float4 default 0,
  specialty text,
  price text,
  status text check (status in ('Available', 'Busy')) default 'Available',
  location text,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Reviews Table
create table reviews (
  id bigint generated by default as identity primary key,
  plumber_id bigint references plumbers(id) on delete cascade not null,
  user_name text not null,
  comment text,
  rating float4 not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Sample Data Insertion
insert into plumbers (name, rating, specialty, price, status, location, image) values
('Ramesh Kumar', 4.8, 'Pipe Fitting', '199', 'Available', 'Old Jalna', 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60'),
('Suresh Patil', 4.5, 'Tank Cleaning', '299', 'Busy', 'New Jalna', 'https://images.unsplash.com/photo-1542596594-649edbc13630?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60'),
('Arun Deshmukh', 4.9, 'Leak Repair', '249', 'Available', 'Jalna MIDC', 'https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60'),
('Vijay Singh', 4.6, 'Installation', '349', 'Available', 'Mantha Road', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60');

-- Enable RLS (Row Level Security) - Optional for now but recommended
alter table plumbers enable row level security;
alter table reviews enable row level security;

-- Create Policies (Public Read Access)
create policy "Public plumbers are viewable by everyone."
  on plumbers for select
  using ( true );

create policy "Public reviews are viewable by everyone."
  on reviews for select
  using ( true );
  
-- Allow public (anyone) to insert reviews
create policy "Public can insert reviews."
  on reviews for insert
  with check ( true );

-- Allow authenticated users (Admin) to insert/update/delete
create policy "Admins can insert plumbers."
  on plumbers for insert
  with check ( auth.role() = 'authenticated' );

create policy "Admins can update plumbers."
  on plumbers for update
  using ( auth.role() = 'authenticated' );

create policy "Admins can delete plumbers."
  on plumbers for delete
  using ( auth.role() = 'authenticated' );

-- ==========================================
-- ADMIN CREATION INSTRUCTION
-- ==========================================
-- To create an Admin user, you should use the Supabase Dashboard:
-- 1. Go to Authentication -> Users
-- 2. Click "Add User"
-- 3. Enter Email (e.g., admin@plumfix.com) and Password.
-- 4. Click "Create User"
-- Use these credentials to login at /admin/login.

-- If you MUST use SQL (e.g. for seeding), you can technically insert into auth.users 
-- but it requires extensive fields (UUID, encrypted password, etc.) which is error-prone manually.
-- The Dashboard is the recommended way.

